### ISSUE TITLE
Attempting to add remark-math leads to fn is not defined.

### ISSUE THREAD

**Issue by parkerziegler** [kitten/react-static-plugin-md-pages#3]
👋 Hey Phil,

I was attempting to add the `remark-math` plugin to support equations on the `renature` docs, adding the following in `static.config.js`:

```js
plugins: [
    [
      'react-static-plugin-md-pages',
      {
        location: './content',
        template: './src/screens/docs',
        pathPrefix: 'docs',
        remarkPlugins: [require('remark-math')],
      },
    ],
    'react-static-plugin-react-router',
    'react-static-plugin-sitemap',
    'react-static-plugin-styled-components',
  ],
```

Doing so results in a Reference Error from `react-static-plugin-md-pages`:

```
fn is not defined
  
  - markdown.js:132 
    [docs]/[react-static-plugin-md-pages]/markdown.js:132:7
```

It appears to be getting hung up here: https://github.com/kitten/react-static-plugin-md-pages/blob/master/src/markdown.js#L97 Searching that file I'm not sure where `fn` is coming from, which appears to be the issue.

For now I'll just bring in the images of the equations, but figured I'd flag it.

**Comment by juandjara** [comment]
I'm having this issue too using `remark-gfm`
Looking at `markdown.js` it looks like you just need to replace `fn` with `processor`
